import type { GetStaticProps, NextPage } from "next"
import Head from "next/head"
import { Client } from "@notionhq/client"
import u from "styles/utils.module.scss"

interface Props {
  posts: any
}

const notion = new Client({ auth: process.env.NOTION_TOKEN })
const databaseId: string = process.env.NOTION_DATABASE_ID

export const getDatabase = async (databaseId: string) => {
  const response = await notion.databases.query({
    database_id: databaseId,
  })
  return response.results
}

export const getStaticProps: GetStaticProps = async () => {
  const database = await getDatabase(databaseId)
  return {
    props: {
      posts: database
    },
    revalidate: 1
  }
}

const Home: NextPage<Props> = ({ posts }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${u.container}`}>
        <pre>{JSON.stringify(posts, undefined, 2)}</pre>
        {/* <pre>Hello</pre> */}
      </div>
    </>
  )
}

export default Home
